FP-349: Main menu - frontend.
fourkitchens/forcepoint-shared-components pull request #14
Opened 2024-02-12 19:04 UTC by robherba

# Ticket(s)

- [FP-349: Main menu - frontend](https://fourkitchens.clickup.com/t/36718269/FP-349)

## Purpose

**This PR does the following:**
Adds a main menu component.

### Functional Testing

- [ ] Run `npm install && npm run dev`
- [ ] Go to main menu page.
- [ ] Validates that the component looks and works as expected

### Accessibility

- [ ] Navigate the secondary menu using a screen reader.
- [ ] Verify the functionality when expanding/collapsing a link with a submenu.

### Notes

- [Main menu design](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?node-id=1562%3A1151&mode=dev)

https://github.com/fourkitchens/forcepoint-shared-components/assets/9342274/2c53769e-c3cc-4745-b69e-d9e0a519bc98

2024-02-12 19:04 UTC, fkbender commented
Task linked: [FP-349 Header main navigation - frontend](https://app.clickup.com/t/36718269/FP-349)

2024-02-12 23:17 UTC, mcortes19 requested changes
Great job @robherba! I just found some minor issues:

- On mobile,  font-size should be `18px`
- **Talk to an expert** button text should be `16px`
- Arrows are breaking in a new line when text is long ![Screenshot 2024-02-12 at 16 52 10](https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/b18e5627-92e9-4708-ba9e-73bbe94adab3)

2024-02-12 23:17 UTC, mcortes19 commented on src/lib/components/02-components/menus/main-menu/main-menu.tsx
> +      console.log('selectedRect', selectedRect)
Remove this console.log

2024-02-12 23:17 UTC, mcortes19 commented on src/lib/components/02-components/menus/main-menu/main-menu.tsx
> +  size?: any;
Does this prop need to be `any`

2024-02-12 23:17 UTC, mcortes19 commented on src/lib/components/02-components/menus/main-menu/main-menu.tsx
> +const possible = [
This variable is not used, could you please review it

2024-02-12 23:20 UTC, mcortes19 commented
Please review conflicts

2024-02-13 21:42 UTC, mcortes19 commented
@robherba please add nav tag with aria label for the entire menu, see: https://www.w3.org/WAI/tutorials/menus/structure/

2024-02-14 16:41 UTC, josue2591 approved these changes
Some minor accessibility adjustments, other than looks good!

2024-02-15 13:13 UTC, merged