FP-280: Callout - FE
fourkitchens/forcepoint-shared-components pull request #24
Opened 2024-03-06 15:50 UTC by robherba

# Ticket(s)

- [FP-280: Callout - FE](https://fourkitchens.clickup.com/t/36718269/FP-280)

## Purpose

**This PR does the following:**
Update link and button styles with figma.

### Functional Testing

- [ ] Run `npm install && npm run dev`
- [ ] Go to the [Callout](http://localhost:6006/?path=/story/components-callout--default) component page 

<img width="1492" alt="Captura de pantalla 2024-03-06 a la(s) 9 43 22 a  m" src="https://github.com/fourkitchens/forcepoint-shared-components/assets/9342274/1bc95a4c-1fce-4e21-b543-0adad4f20c0c">

<img width="1495" alt="Captura de pantalla 2024-03-06 a la(s) 9 45 02 a  m" src="https://github.com/fourkitchens/forcepoint-shared-components/assets/9342274/a1f7c3d3-f8fb-429f-84bf-3716d8475190">

### Notes

- [Design](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2290-137029&mode=design&t=VPCJlAhLZR8m1302-0)

2024-03-06 15:50 UTC, fkbender commented
Task linked: [FP-280 Callout - FE](https://app.clickup.com/t/36718269/FP-280)

2024-03-07 14:15 UTC, mcortes19 requested changes
@robherba Great work! 
I found some issues need to be addressed:

- We need to be able to pass a `next/link` component for the CTA button.
- `Viola` and `Navy` variants don't work
- Heading `font-weight` should be `600`

Also, take a look at other comments I left

2024-03-07 14:15 UTC, mcortes19 commented on tailwind-theme-preset.js
> +      aspectRatio: {
You don't have to define those aspect ratio, the theme already have configured all of them. See line 7

We might need to add a wrapper to the image and set the `aspect ratio` when we use `next/image`, so we might need to do some testing on implementing this in Next.js

2024-03-07 17:57 UTC, mcortes19 approved these changes

2024-03-07 17:58 UTC, merged