FP-740: Create Form styles
fourkitchens/forcepoint-shared-components pull request #27
Opened 2024-03-11 18:12 UTC by gstvdesign

# Ticket(s)

- [FP-740: Create Form styles](https://fourkitchens.clickup.com/t/86a2g7cxp)

## Purpose

* Create styles for hubspot forms

**This PR does the following:**

* create the form styles
* create necessary stories for input, selectfield, radio button, and checkbox
* export styles to be used in other apps
* create necessary icons for selectfield and checkbox

### Functional Testing

- [ ] Checkout to this branch and run `npm install && npm run dev`
- [ ] Look for the form components

![Screenshot 2024-03-11 at 15 09 42](https://github.com/fourkitchens/forcepoint-shared-components/assets/8851324/5b5ace27-551f-46a4-af58-4d553987c17b)
![Screenshot 2024-03-11 at 15 09 50](https://github.com/fourkitchens/forcepoint-shared-components/assets/8851324/0a07a2bc-7dca-45a6-8b57-e590ee5b07b8)
![Screenshot 2024-03-11 at 15 10 05](https://github.com/fourkitchens/forcepoint-shared-components/assets/8851324/e3e4ed77-e498-48a7-bfa5-b9924589f12c)
![Screenshot 2024-03-11 at 15 10 20](https://github.com/fourkitchens/forcepoint-shared-components/assets/8851324/8a399f46-904a-4ead-9582-e6a430e91ad7)

2024-03-11 18:12 UTC, fkbender commented
Task linked: [FP-740 Create Form styles](https://app.clickup.com/t/36718269/FP-740)

2024-03-14 05:24 UTC, mcortes19 requested changes
@gstvdesign great work! 

I just found some issues need to be fixed

I linked this branch to my local version of Next.js to test out the sign-up form and noticed the following:

- We need to add space between each form field: you could use the following
![Screenshot 2024-03-13 at 23 13 41](https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/3e5e8daa-59a6-4022-8d6a-18bd79800c5a)

You could use the following snippet:
```css
.hubspot-form-wrapper form > div:not(:last-of-type) {
  @apply mb-md;
}
```

- Error message is not correctly aligned: 
![Screenshot 2024-03-13 at 23 13 50](https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/d518de6a-acab-4c8d-9011-e1b89ee3f85e)

2024-03-14 05:24 UTC, mcortes19 commented on src/lib/assets/css/form.css
@gstvdesign could you please configure your text editor to always add an empty line at the end of the file?

2024-03-14 05:24 UTC, mcortes19 commented on src/lib/assets/css/form.css
> +@tailwind base;
I think you don't need to add `@tailwind` imports again

2024-03-14 05:28 UTC, mcortes19 requested changes

2024-03-14 05:28 UTC, mcortes19 commented on src/lib/assets/css/form.css
> +  @apply block w-full px-5 py-3 border border-brumosa rounded-m text-grey outline-none focus:rounded-m focus:px-5 focus:py-3 focus:border-teal focus:border-2 focus:border-teal;
Remove duplicated `focus:border-teal` class

2024-03-15 13:32 UTC, gstvdesign commented
> ```css
> .hubspot-form-wrapper form > div:not(:last-of-type) {
>   @apply mb-md;
> }
> ```

Thanks for the feedback!

Space added:
![Screenshot 2024-03-15 at 10 31 19](https://github.com/fourkitchens/forcepoint-shared-components/assets/8851324/6dbcfaba-48c4-4210-bdce-fccb98d17ae2)

Error message aligned properly:
![Screenshot 2024-03-15 at 10 31 50](https://github.com/fourkitchens/forcepoint-shared-components/assets/8851324/36e8d1c4-6d9f-490a-be38-a1bc1ce7bd83)

2024-03-18 14:25 UTC, mcortes19 approved these changes
@gstvdesign works like a charm 🎖️

2024-03-18 14:25 UTC, merged