FP-301: Image and Content Slide and Slider - FED
fourkitchens/forcepoint-shared-components pull request #38
Opened 2024-03-25 19:05 UTC by gstvdesign

# Ticket(s)

- [FP-XX: Title](https://fourkitchens.clickup.com/t/36718269/FP-XXX)

## Purpose

**This PR does the following:**

- Creates Image and content slider

### Functional Testing

- [ ] run `npm run dev`
- [ ] Go to the [Accordion Slider](http://localhost:6006/?path=/story/components-sliders-accordion-slider--default)
- [ ] Compare to [the design](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=1675-46044&mode=design&t=vlNowAUuiYZbnNUS-0)
- [ ] Click on the slider title to close the open accordion and change the current slide
- [ ] Hover over the accordion to stop the automatic change of the slider

### Readme Updates

- Add link to documentation

### Accessibility

- Check accessibility

2024-03-25 19:05 UTC, fkbender commented
Task linked: [FP-301 Image and Content Slide and Slider - FED](https://app.clickup.com/t/36718269/FP-301)

2024-04-03 16:11 UTC, mcortes19 requested changes
@gstvdesign great job!  
I found some issues need to be addressed:

## Mobile
- It should be full-width on mobile
- Image should be first item on mobile
- Current ![Screenshot 2024-04-03 at 08 06 07](https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/0f01742a-47cc-4f66-81e7-70303ed38031)
- Designs ![Designs](https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/906663b6-43a4-42b6-804b-a8cf27324bfb)

## Desktop
- There's a weird transition image between elements on desktop
https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/94d79b3a-67cd-4100-bcf9-eb4be948e03e

- Sometimes the slide timer does't work properly and change to next slide so quick


## General
- There's a missing `viola` color version of this component
- Missing arrows prefixing the Accordion item
### Accordion Slider title
- I don't see styles for this item on Figma, I think we should ask to Victor if he can include them. Anyways, It's using a `<p>` when it should use a `<h2>`,  also, we need to add the right styles for `h2` title elements. 

### Accordion Slider subtilte
- I don't see styles for this item on Figma, I think we should ask to Victor if he can include them. Anyways, It's using a `<p>` when it should use a `<h3>`,  also, we need to add the right styles for `h3` title elements. 

### Accordion item
- Inactive item in black theme should use `brumosa` color
- Active item in black theme should use `white`
- CTA styles don't match with designs
![Screenshot 2024-04-03 at 09 04 35](https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/88fad494-1b7c-4c96-a399-3c517d5a5074)

![Screenshot 2024-04-03 at 09 03 43](https://github.com/fourkitchens/forcepoint-shared-components/assets/11282049/6400ef20-c94a-4f31-9a11-1a78a5ed459b)
1b7-b22d9fa8c0f7)

2024-04-08 18:17 UTC, gstvdesign commented on src/lib/components/02-components/slider/content-slider.tsx
> +}: ContentSliderProps) {
I renamed the component to match the drupal paragraph and forgot to rename this component. I'll review everything accordingly

2024-04-18 22:15 UTC, mcortes19 approved these changes

2024-04-18 22:15 UTC, merged