feat(fp-351) branding component created
fourkitchens/forcepoint-shared-components pull request #4
Opened 2024-01-19 11:57 UTC by josue2591

# Ticket(s)

- [FP-XX: Title](https://fourkitchens.clickup.com/t/36718269/FP-XXX)

## Purpose
- Create the branding component
- In the [design](https://www.figma.com/file/wjvtxxU9UCb8Z1rM67ihYt/Assets?node-id=2%3A712&mode=dev) there are 4 "Logos" so this branding component was implemented to display any of those

### Functional Testing

- [ ] Go to http://localhost:6006/?path=/story/elements-branding--default
- [ ] The branding component should look like the video shows
- [ ] It should allow to overwrite the href, the alt value and the image 

Video: https://www.loom.com/share/12bf158b79f248eca02a21935b6d2bc8?sid=4f63f918-f2c4-4072-a083-c0567b5cf271

2024-01-19 11:57 UTC, fkbender commented
Task linked: [FP-351 Header logo](https://app.clickup.com/t/36718269/FP-351)

2024-01-29 15:22 UTC, cienvaras requested changes
Looks great, just a little detail to fix.

2024-01-29 15:22 UTC, cienvaras commented on src/lib/components/02-components/branding/branding.tsx
> +        alt={`${alt}`}
No need to use a template literal here.

```suggestion
        alt={alt}
```

2024-01-31 16:21 UTC, mcortes19 approved these changes
@josue2591 LGTM 🎖️

2024-01-31 16:29 UTC, merged