FP-294:  Featured resource.
fourkitchens/forcepoint-shared-components pull request #53
Opened 2024-04-24 17:44 UTC by robherba

# Ticket(s)

- [FP-376:  Featured resource](https://fourkitchens.clickup.com/t/36718269/FP-376)

## Purpose

**This PR does the following:**

- Adds a `featured resource` component.

### Functional Testing

- [ ] Navigate to`featured resource` page on storybook.
- [ ] Validate that everything looks and functions as expected.

### Dependencies:

- https://github.com/fourkitchens/forcepoint-nextjs-page-router/pull/55
- https://github.com/fourkitchens/forcepoint-drupal/pull/93

### Design

- [Card version](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2256-129374&mode=design&t=aDa2TsAcVKMllX9K-0)

- [List version](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2269-129495&mode=design&t=aDa2TsAcVKMllX9K-0)

2024-04-24 17:44 UTC, fkbender commented
Task linked: [FP-294 Featured Resource - FED](https://app.clickup.com/t/36718269/FP-294)
Task linked: [FP-376 Featured Resource - BED](https://app.clickup.com/t/36718269/FP-376)

2024-04-26 04:20 UTC, robert-arias requested changes
Everything looks good toca! Just some observations.

2024-04-26 04:39 UTC, robert-arias commented
Also, Should the lists have a text below the title?
<img width="915" alt="image" src="https://github.com/fourkitchens/forcepoint-shared-components/assets/37127345/b5902593-8f9c-4e50-a356-42810ba35f63">

2024-04-29 15:20 UTC, robherba commented on src/lib/components/02-components/featured-resource/featured-resource--card.tsx
> +          <span className="text-h3 font-[600] text-black md:text-h4">
Hi Toca, thanks for capturing this. It seems the font size changes depending on the device size (mobile: 24px / desktop: 20px). Please check out this URL and let me know if it makes sense or if you recommend making adjustments: [[**Figma Link**](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2247-127303&mode=design&t=E5hmSSnYa8iKqFrL-4)]

2024-04-29 15:31 UTC, robherba commented
> Also, Shouldn't the lists have a text below the title? <img alt="image" width="915" src="https://private-user-images.githubusercontent.com/37127345/325850299-b5902593-8f9c-4e50-a356-42810ba35f63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDM0NDQsIm5iZiI6MTcxNDQwMzE0NCwicGF0aCI6Ii8zNzEyNzM0NS8zMjU4NTAyOTktYjU5MDI1OTMtOGY5Yy00ZTUwLWEzNTYtNDI4MTBiYTM1ZjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE1MDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5N2UyOTk5ZTNiYzRiZWQzNzEwODg2ZjhhYWFiODcxY2ZmMmQ2NDdiOWFiOTY5OThkZTBjZDU2ZjhmYmIzZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FGDtOtLVJ5ApC_gZGnLlkI4t-Ife6AXKY8EaqdpnlCA">

I had the same question too. In a chat with Marvin and Duncan, we discussed the list version component. The styles for this version are in Link A, while those in Link B are for a different component. Also, I talked to Duncan separately about the icons we should use, and he suggested using the ones from Link C.

[Link A](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2252-127847&mode=design&t=qw517ZtAiR0CAXvK-4)

[Link B](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2252-128631&mode=design&t=qw517ZtAiR0CAXvK-4)

[Link C](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=4263-11044&mode=design&t=YCjWfvmsFZqKU0IU-4)

2024-05-02 16:57 UTC, merged